import { uiText, useLocale } from './i18n';
import { Plus, Swords, X } from 'lucide-react';

type Gear={id:string;name:string;description:string;kind:'ordinary'|'consumable'|'weapon'|'armor';price:number;power:number;restores:'hp'|'vitality'};
type Stock={item_id:string;quantity:number};
export type Rules={system:'story-lite'|'d20'|'d100';hp:number;coins:number;vitality:number;attack_bonus:number;defense:number;damage:number;percentile_skill:number;party_limit:number;recruitable:number[];
  items:Gear[];starting_items:{item_id:string;quantity:number;holder:string}[];
  shops:{id:string;name:string;location:number;stock:Stock[];buyback:boolean}[];
  enemies:{id:string;name:string;description:string;location:number;hp:number;defense:number;attack_bonus:number;damage:number;reward_coins:number;reward_xp:number}[]};

const fresh=():Rules=>({system:'d20',hp:20,coins:20,vitality:10,attack_bonus:2,defense:10,damage:3,percentile_skill:60,party_limit:4,recruitable:[],items:[],starting_items:[],shops:[],enemies:[]});
const uid=(prefix:string)=>prefix+'_'+crypto.randomUUID().replaceAll('-','').slice(0,12);
function NumberField({label,value,onChange,min=0,max=9999}:{label:string;value:number;onChange:(n:number)=>void;min?:number;max?:number}){
  useLocale();
  return <label className="studio-field">{label}<input type="number" aria-label={label} min={min} max={max} value={value} onChange={e=>onChange(Number(e.target.value))}/></label>;
}

export function RuleEditor({value,onChange,locations,characters}:{value?:Rules|null;onChange:(r:Rules|null)=>void;locations:{name:string}[];characters:{name:string}[]}){
  useLocale();
  const edit=(fn:(r:Rules)=>void)=>{const r=structuredClone(value||fresh());fn(r);onChange(r);};
  const place=(label:string,selected:number,change:(n:number)=>void)=><label className="studio-field">{label}<select aria-label={label} value={selected} onChange={e=>change(Number(e.target.value))}>{locations.map((p,i)=><option key={i} value={i}>{p.name}</option>)}</select></label>;
  const gear=(label:string,selected:string,change:(id:string)=>void)=><label className="studio-field">{label}<select aria-label={label} value={selected} onChange={e=>change(e.target.value)}>{value?.items.map(i=><option key={i.id} value={i.id}>{i.name}</option>)}</select></label>;
  return <section className="rules-editor"><h3><Swords size={19}/>{uiText("RuleEditor.001")}</h3>
    {!value?<><p className="tiny-muted">{uiText("RuleEditor.002")}</p><button className="secondary" onClick={()=>onChange(fresh())}>{uiText("RuleEditor.003")}</button></>:<>
      <div className="form-grid"><label className="studio-field">{uiText("RuleEditor.004")}<select aria-label={uiText("RuleEditor.004")} value={value.system} onChange={e=>edit(r=>{r.system=e.target.value as Rules['system'];})}><option value="story-lite">{uiText("RuleEditor.005")}</option><option value="d20">{uiText("RuleEditor.006")}</option><option value="d100">{uiText("RuleEditor.007")}</option></select></label><NumberField label={uiText("RuleEditor.066")} value={value.coins} onChange={n=>edit(r=>{r.coins=n;})}/><NumberField label={uiText("RuleEditor.065")} value={value.hp} min={1} max={200} onChange={n=>edit(r=>{r.hp=n;})}/><NumberField label={uiText("RuleEditor.064")} value={value.vitality} min={1} max={100} onChange={n=>edit(r=>{r.vitality=n;})}/><NumberField label={uiText("RuleEditor.063")} value={value.damage} min={1} max={20} onChange={n=>edit(r=>{r.damage=n;})}/><NumberField label={uiText("RuleEditor.062")} value={value.defense} min={5} max={25} onChange={n=>edit(r=>{r.defense=n;})}/><NumberField label={uiText("RuleEditor.061")} value={value.attack_bonus} max={12} onChange={n=>edit(r=>{r.attack_bonus=n;})}/>{value.system==='d100'&&<NumberField label={uiText("RuleEditor.060")} value={value.percentile_skill} min={1} max={95} onChange={n=>edit(r=>{r.percentile_skill=n;})}/>}</div>
      <p className="tiny-muted">{uiText("RuleEditor.008")}</p>
      <h4>{uiText("RuleEditor.009")}</h4><button className="secondary" onClick={()=>edit(r=>{r.items.push({id:uid('gear'),name:uiText("RuleEditor.059"),description:'',kind:'ordinary',price:1,power:1,restores:'hp'});})}><Plus size={14}/>{uiText("RuleEditor.010")}</button>
      {value.items.map((item,i)=><details className="editor-block" key={item.id}><summary>{item.name}</summary><div className="form-grid"><label className="studio-field">{uiText("RuleEditor.011")}<input value={item.name} maxLength={80} onChange={e=>edit(r=>{r.items[i].name=e.target.value;})}/></label><label className="studio-field">{uiText("RuleEditor.012")}<select value={item.kind} onChange={e=>edit(r=>{r.items[i].kind=e.target.value as Gear['kind'];})}><option value="ordinary">{uiText("RuleEditor.013")}</option><option value="consumable">{uiText("RuleEditor.014")}</option><option value="weapon">{uiText("RuleEditor.015")}</option><option value="armor">{uiText("RuleEditor.016")}</option></select></label><NumberField label={uiText("RuleEditor.058")} value={item.price} onChange={n=>edit(r=>{r.items[i].price=n;})}/><NumberField label={item.kind==='consumable'?uiText("RuleEditor.057"):item.kind==='armor'?uiText("RuleEditor.056"):uiText("RuleEditor.055")} value={item.power} max={20} onChange={n=>edit(r=>{r.items[i].power=n;})}/>{item.kind==='consumable'&&<label className="studio-field">{uiText("RuleEditor.017")}<select value={item.restores} onChange={e=>edit(r=>{r.items[i].restores=e.target.value as Gear['restores'];})}><option value="hp">{uiText("RuleEditor.018")}</option><option value="vitality">{uiText("RoomPanel.066")}</option></select></label>}</div><label className="studio-field">{uiText("RuleEditor.019")}<textarea value={item.description} maxLength={500} onChange={e=>edit(r=>{r.items[i].description=e.target.value;})}/></label><button className="quiet-button" onClick={()=>edit(r=>{r.items.splice(i,1);r.starting_items=r.starting_items.filter(s=>s.item_id!==item.id);r.shops.forEach(s=>{s.stock=s.stock.filter(x=>x.item_id!==item.id);});})}><X size={14}/>{uiText("RuleEditor.020")}</button></details>)}
      <h4>{uiText("RuleEditor.021")}</h4><button className="secondary" disabled={!value.items.length} onClick={()=>edit(r=>{r.starting_items.push({item_id:r.items[0].id,holder:'player',quantity:1});})}>{uiText("RuleEditor.022")}</button>
      {value.starting_items.map((item,i)=><div className="form-grid editor-block" key={i}>{gear(uiText("RuleEditor.054"),item.item_id,id=>edit(r=>{r.starting_items[i].item_id=id;}))}<NumberField label={uiText("RuleEditor.053")} value={item.quantity} min={1} max={99} onChange={n=>edit(r=>{r.starting_items[i].quantity=n;})}/><label className="studio-field">{uiText("RuleEditor.023")}<select value={item.holder} onChange={e=>edit(r=>{r.starting_items[i].holder=e.target.value;})}><option value="player">{uiText("RuleEditor.024")}</option>{characters.map((a,j)=><option key={'n'+j} value={'npc_'+j}>{a.name}</option>)}{locations.map((p,j)=><option key={'l'+j} value={'loc_'+j}>{uiText("RuleEditor.025", {p0: (p.name)})}</option>)}</select></label><button className="quiet-button" onClick={()=>edit(r=>{r.starting_items.splice(i,1);})}>{uiText("RuleEditor.026")}</button></div>)}
      <h4>{uiText("RuleEditor.027")}</h4><button className="secondary" onClick={()=>edit(r=>{r.shops.push({id:uid('shop'),name:uiText("RuleEditor.052"),location:0,stock:[],buyback:true});})}>{uiText("RuleEditor.028")}</button>
      {value.shops.map((shop,i)=><details className="editor-block" key={shop.id}><summary>{shop.name}</summary><label className="studio-field">{uiText("RuleEditor.029")}<input value={shop.name} onChange={e=>edit(r=>{r.shops[i].name=e.target.value;})}/></label>{place(uiText("RuleEditor.051"),shop.location,n=>edit(r=>{r.shops[i].location=n;}))}<label className="checkboxes"><input type="checkbox" checked={shop.buyback} onChange={e=>edit(r=>{r.shops[i].buyback=e.target.checked;})}/>{uiText("RuleEditor.030")}</label>{value.items.map(item=>{const entry=shop.stock.find(s=>s.item_id===item.id);return <div className="stock-editor" key={item.id}><label><input type="checkbox" checked={!!entry} onChange={e=>edit(r=>{r.shops[i].stock=e.target.checked?[...r.shops[i].stock,{item_id:item.id,quantity:5}]:r.shops[i].stock.filter(s=>s.item_id!==item.id);})}/>{item.name}</label>{entry&&<NumberField label={uiText("RuleEditor.050")} value={entry.quantity} max={99} onChange={n=>edit(r=>{r.shops[i].stock.find(s=>s.item_id===item.id)!.quantity=n;})}/>}</div>;})}<button className="quiet-button" onClick={()=>edit(r=>{r.shops.splice(i,1);})}>{uiText("RuleEditor.031")}</button></details>)}
      <h4>{uiText("RuleEditor.032")}</h4><button className="secondary" onClick={()=>edit(r=>{r.enemies.push({id:uid('enemy'),name:uiText("RuleEditor.049"),description:uiText("RuleEditor.048"),location:1,hp:12,defense:10,attack_bonus:2,damage:3,reward_coins:3,reward_xp:5});})}>{uiText("RuleEditor.033")}</button>
      {value.enemies.map((enemy,i)=><details className="editor-block" key={enemy.id}><summary>{enemy.name}</summary><label className="studio-field">{uiText("RuleEditor.034")}<input value={enemy.name} onChange={e=>edit(r=>{r.enemies[i].name=e.target.value;})}/></label><label className="studio-field">{uiText("RuleEditor.035")}<textarea value={enemy.description} maxLength={500} onChange={e=>edit(r=>{r.enemies[i].description=e.target.value;})}/></label>{place(uiText("RuleEditor.047"),enemy.location,n=>edit(r=>{r.enemies[i].location=n;}))}<div className="form-grid">{(['hp','defense','attack_bonus','damage','reward_coins','reward_xp'] as const).map((key,j)=><NumberField key={key} label={[uiText("RuleEditor.046"),uiText("RuleEditor.045"),uiText("RuleEditor.044"),uiText("RuleEditor.043"),uiText("RuleEditor.042"),uiText("RuleEditor.041")][j]} value={enemy[key]} min={key==='hp'||key==='damage'?1:key==='defense'?5:0} max={key==='hp'?200:key==='defense'?25:key==='attack_bonus'?12:key==='damage'?20:100} onChange={n=>edit(r=>{r.enemies[i][key]=n;})}/>)}</div><button className="quiet-button" onClick={()=>edit(r=>{r.enemies.splice(i,1);})}>{uiText("RuleEditor.036")}</button></details>)}
      <h4>{uiText("RuleEditor.037")}</h4><NumberField label={uiText("RuleEditor.040")} value={value.party_limit} min={1} max={6} onChange={n=>edit(r=>{r.party_limit=n;})}/><div className="checkboxes">{characters.map((actor,i)=><label key={i}><input type="checkbox" checked={value.recruitable.includes(i)} onChange={e=>edit(r=>{r.recruitable=e.target.checked?[...r.recruitable,i]:r.recruitable.filter(n=>n!==i);})}/>{actor.name}</label>)}</div><p className="tiny-muted">{uiText("RuleEditor.038")}</p>
      <button className="quiet-button" onClick={()=>onChange(null)}>{uiText("RuleEditor.039")}</button>
    </>}
  </section>;
}
