import { uiText, useLocale } from './i18n';
import { Plus, X } from 'lucide-react';

type Resident={name:string;role:string;personality:string;goal:string;boundary:string;secret:string};
type Expansion={name:string;description:string;connects_to:number;resident?:Resident|null};
type Faction={id:string;name:string;goal:string;interval_s:number;threshold:number;outcome:string;expansion?:Expansion|null};
export type Simulation={interval_s:number;actor_indices:number[];factions:Faction[]};
export function SimulationEditor({value,locations,characters,onChange}:{value?:Simulation|null;locations:{name:string}[];characters:{name:string}[];onChange:(value:Simulation|null)=>void}){
  useLocale();
  const change=(fn:(value:Simulation)=>void)=>{if(value){const next=structuredClone(value);fn(next);onChange(next);}};
  return <section className="rules-editor simulation-editor"><h3>{uiText("SimulationEditor.001")}</h3><label><input type="checkbox" checked={!!value} onChange={e=>onChange(e.target.checked?{interval_s:600,actor_indices:[0],factions:[]}:null)}/>{uiText("SimulationEditor.002")}</label><p className="tiny-muted">{uiText("SimulationEditor.003")}</p>{value&&<>
    <label className="studio-field">{uiText("SimulationEditor.004")}<input type="number" min={300} max={3600} value={value.interval_s} onChange={e=>change(v=>{v.interval_s=Number(e.target.value);})}/></label>
    <div className="checkboxes">{characters.map((c,i)=><label key={i}><input type="checkbox" checked={value.actor_indices.includes(i)} onChange={e=>change(v=>{v.actor_indices=e.target.checked?[...v.actor_indices,i]:v.actor_indices.filter(x=>x!==i);})}/>{uiText("SimulationEditor.005", {p0: (c.name)})}</label>)}</div>
    <h4>{uiText("SimulationEditor.006")}</h4>{value.factions.map((f,i)=><details className="editor-block" key={f.id}><summary>{f.name}</summary><button className="quiet-button" onClick={()=>change(v=>{v.factions.splice(i,1);})}><X size={12}/>{uiText("SimulationEditor.007")}</button>{(['name','goal','outcome'] as const).map((key,j)=><label className="studio-field" key={key}>{[uiText("SimulationEditor.034"),uiText("SimulationEditor.021"),uiText("SimulationEditor.033")][j]}<textarea maxLength={key==='name'?60:600} value={f[key]} onChange={e=>change(v=>{v.factions[i][key]=e.target.value;})}/></label>)}<div className="form-grid"><label className="studio-field">{uiText("SimulationEditor.008")}<input type="number" min={300} max={7200} value={f.interval_s} onChange={e=>change(v=>{v.factions[i].interval_s=Number(e.target.value);})}/></label><label className="studio-field">{uiText("SimulationEditor.009")}<input type="number" min={2} max={24} value={f.threshold} onChange={e=>change(v=>{v.factions[i].threshold=Number(e.target.value);})}/></label></div>
      <label><input type="checkbox" checked={!!f.expansion} onChange={e=>change(v=>{v.factions[i].expansion=e.target.checked?{name:uiText("SimulationEditor.032"),description:uiText("SimulationEditor.031"),connects_to:0}:null;})}/>{uiText("SimulationEditor.010")}</label>
      {f.expansion&&<><label className="studio-field">{uiText("SimulationEditor.011")}<input maxLength={60} value={f.expansion.name} onChange={e=>change(v=>{v.factions[i].expansion!.name=e.target.value;})}/></label><label className="studio-field">{uiText("SimulationEditor.012")}<textarea maxLength={600} value={f.expansion.description} onChange={e=>change(v=>{v.factions[i].expansion!.description=e.target.value;})}/></label><label className="studio-field">{uiText("SimulationEditor.013")}<select value={f.expansion.connects_to} onChange={e=>change(v=>{v.factions[i].expansion!.connects_to=Number(e.target.value);})}>{locations.map((l,j)=><option value={j} key={j}>{l.name}</option>)}</select></label>
      <label><input type="checkbox" checked={!!f.expansion.resident} onChange={e=>change(v=>{v.factions[i].expansion!.resident=e.target.checked?{name:uiText("SimulationEditor.030"),role:uiText("SimulationEditor.029"),personality:uiText("SimulationEditor.028"),goal:uiText("SimulationEditor.027"),boundary:uiText("SimulationEditor.026"),secret:uiText("SimulationEditor.025")}:null;})}/>{uiText("SimulationEditor.014")}</label>{f.expansion.resident&&(['name','role','personality','goal','boundary','secret'] as const).map((key,j)=><label className="studio-field" key={key}>{[uiText("SimulationEditor.024"),uiText("SimulationEditor.023"),uiText("SimulationEditor.022"),uiText("SimulationEditor.021"),uiText("SimulationEditor.020"),uiText("SimulationEditor.019")][j]}<textarea maxLength={j<2?60:600} value={f.expansion!.resident![key]} onChange={e=>change(v=>{v.factions[i].expansion!.resident![key]=e.target.value;})}/></label>)}</>}
    </details>)}<button className="secondary" disabled={value.factions.length>=8} onClick={()=>change(v=>{v.factions.push({id:'f_'+crypto.randomUUID().slice(0,8),name:uiText("SimulationEditor.018"),goal:uiText("SimulationEditor.017"),interval_s:900,threshold:4,outcome:uiText("SimulationEditor.016")});})}><Plus size={14}/>{uiText("SimulationEditor.015")}</button>
  </>}</section>;
}
