import { uiText, useLocale } from './i18n';
import { useState } from 'react';

type Value = number | boolean | string;
type Variable = {id:string;name:string;kind:'integer'|'boolean'|'enum';initial:Value;minimum:number;maximum:number;options:string[];visibility:'public'|'player'|'gm'};
type Condition = {source:string;key:string|null;actor_id:string;op:string;value:Value};
type Effect = {kind:string;target:string|null;actor_id:string;value:Value;text:string};
type Action = {id:string;name:string;description:string;location_id:string|null;when_all:Condition[];when_any:Condition[];effects:Effect[];once:boolean;cooldown_s:number;time_cost_s:number};
type Trigger = {id:string;name:string;on:string;target_id:string|null;when_all:Condition[];when_any:Condition[];effects:Effect[];once:boolean;cooldown_s:number};
type Step = {kind:string;target_id:string|null;seconds:number};
type Scenario = {name:string;steps:Step[];expect:Condition[]};
export type StateRules = {variables:Variable[];actions:Action[];triggers:Trigger[];tests:Scenario[]};
type Named = {name?:string;title?:string;id?:string};
type Props = {hasStartingItem?:boolean;hasPressure?:boolean;value?:StateRules|null;onChange:(v:StateRules|null)=>void;locations:Named[];characters:Named[];clues?:Named[];challenges?:Named[];items?:Named[];enemies?:Named[];inherited?:StateRules|null;scope:'world'|'story'};
const empty = ():StateRules=>({variables:[],actions:[],triggers:[],tests:[]});
const pc='pc_traveler';
const condition=(id:string):Condition=>({source:'variable',key:id,actor_id:pc,op:'ge',value:1});
const effect=(id:string):Effect=>({kind:'add',target:id,actor_id:pc,value:1,text:''});
const ident=(prefix:string)=>prefix+'_'+crypto.randomUUID().replaceAll('-','').slice(0,8);
const sourceNames:Record<string,string>={get variable() { return uiText("StateEditor.143"); },get resource() { return uiText("StateEditor.142"); },get item_count() { return uiText("StateEditor.141"); },get location() { return uiText("StateEditor.140"); },get knowledge() { return uiText("RoomPanel.029"); },get quest() { return uiText("StateEditor.139"); },get clock() { return uiText("StateEditor.138"); },get party() { return uiText("StateEditor.137"); },get game_time() { return uiText("StateEditor.136"); }};
const kinds:Record<string,string>={get set() { return uiText("StateEditor.135"); },get add() { return uiText("StateEditor.134"); },get resource() { return uiText("StateEditor.133"); },get clock() { return uiText("StateEditor.132"); },get reveal() { return uiText("StateEditor.131"); },get message() { return uiText("StateEditor.130"); }};

function Input({label,value,onChange,type='text'}:{label:string;value:string|number;onChange:(v:string)=>void;type?:string}){
  useLocale();
  return <label className="studio-field">{label}<input aria-label={label} type={type} value={value} onChange={e=>onChange(e.target.value)}/></label>;
}
function Select({label,value,options,onChange}:{label:string;value:string;options:[string,string][];onChange:(v:string)=>void}){
  useLocale();
  return <label className="studio-field">{label}<select aria-label={label} value={value} onChange={e=>onChange(e.target.value)}>{!options.some(([v])=>v===value)&&<option value={value}>{value||uiText("StateEditor.129")}</option>}{options.map(([v,n])=><option key={v} value={v}>{n}</option>)}</select></label>;
}
function Scalar({label,value,onChange,options}:{label:string;value:Value;onChange:(v:Value)=>void;options?:string[]}){
  useLocale();
  if(typeof value==='boolean')return <Select label={label} value={String(value)} options={[["true",uiText("StateEditor.128")],["false",uiText("StateEditor.127")]]} onChange={v=>onChange(v==='true')}/>;
  if(options?.length)return <Select label={label} value={String(value)} options={options.map(v=>[v,v])} onChange={onChange}/>;
  return <Input label={label} value={value} type={typeof value==='number'?'number':'text'} onChange={v=>onChange(typeof value==='number'?Number(v)||0:v)}/>;
}

export function StateEditor(props:Props){
  useLocale();
  const {value,onChange,scope}=props;
  const [open,setOpen]=useState(false);
  // Native/community packages may omit optional defaults; edits send a complete typed pack.
  const fullCondition=(c:Condition):Condition=>Object.assign({key:null,actor_id:pc,op:'eq'},c);
  const fullEffect=(e:Effect):Effect=>Object.assign({target:null,actor_id:pc,value:0,text:''},e);
  const pack:StateRules={...empty(),...value,
    variables:(value?.variables||[]).map(v=>Object.assign({kind:'integer',initial:0,minimum:0,maximum:100,options:[],visibility:'public'},v) as Variable),
    actions:(value?.actions||[]).map(a=>Object.assign({description:'',location_id:null,once:false,cooldown_s:0,time_cost_s:60},a,{when_all:(a.when_all||[]).map(fullCondition),when_any:(a.when_any||[]).map(fullCondition),effects:a.effects.map(fullEffect)})),
    triggers:(value?.triggers||[]).map(t=>Object.assign({on:'turn',target_id:null,once:true,cooldown_s:0},t,{when_all:(t.when_all||[]).map(fullCondition),when_any:(t.when_any||[]).map(fullCondition),effects:t.effects.map(fullEffect)})),
    tests:(value?.tests||[]).map(t=>({...t,expect:t.expect.map(fullCondition),steps:t.steps.map(s=>Object.assign({target_id:null,seconds:60},s))}))};
  const change=(fn:(p:StateRules)=>void)=>{const next=structuredClone(pack);fn(next);onChange(next);};
  const variables=[...props.inherited?.variables||[],...pack.variables];
  const locs:[string,string][]=props.locations.map((v,i)=>['loc_'+i,v.name||uiText("StateEditor.126")]);
  const actors:[string,string][]=[[pc,uiText("StateEditor.035")],...props.characters.map((v,i):[string,string]=>['npc_'+i,v.name||uiText("StateEditor.123")])];
  const facts:[string,string][]=[['fact_setting',uiText("StateEditor.125")],...props.characters.map((v,i):[string,string]=>['fact_secret_'+i,uiText("StateEditor.124", {p0: ((v.name||uiText("StateEditor.123")))})]),...props.clues?.map((v,i):[string,string]=>['fact_clue_'+i,v.title||uiText("StateEditor.122")])||[]];
  const targets=(source:string):[string,string][]=>source==='variable'?variables.map(v=>[v.id,v.name]):source==='resource'?[['coins',uiText("RoomPanel.065")],['hp',uiText("RuleEditor.018")],['vitality',uiText("RoomPanel.066")],['xp',uiText("StateEditor.121")]]:source==='knowledge'?facts:source==='quest'?(props.challenges||[]).map((v,i)=>['quest_'+i,v.title||uiText("SimulationEditor.021")]):source==='clock'?(scope==='story'&&props.hasPressure!==false?[['clock_pressure',uiText("StateEditor.120")]]:[]):source==='party'?actors:source==='item_count'?[...(scope==='story'&&props.hasStartingItem!==false?[['item_start',uiText("StateEditor.119")]] as [string,string][]:[]),...props.items?.map((v):[string,string]=>[v.id||'',v.name||uiText("StateEditor.118")])||[]]:[];
  const first=variables[0]?.id||'';
  const freshEffect=():Effect=>({...effect(first),kind:'set',value:variables[0]?.initial??0});
  const conditions=(rows:Condition[],set:(v:Condition[])=>void,label:string)=><div className="state-subform"><strong>{label}</strong>{rows.map((c,i)=>{
    const update=(patch:Partial<Condition>)=>set(rows.map((v,j)=>i===j?{...v,...patch}:v));
    const variable=variables.find(v=>v.id===c.key);
    return <div className="state-row" key={i}><Select label={uiText("StateEditor.117")} value={c.source} options={Object.entries(sourceNames)} onChange={source=>{const key=targets(source)[0]?.[0]||null;const initial=source==='variable'?variables.find(v=>v.id===key)?.initial??0:['knowledge','party'].includes(source)?true:source==='location'?locs[0][0]:source==='quest'?'completed':0;update({source,key,op:typeof initial==='number'?'ge':'eq',value:initial});}}/>{targets(c.source).length>0&&<Select label={uiText("StateEditor.116")} value={c.key||''} options={targets(c.source)} onChange={key=>update({key,...(c.source==='variable'?{value:variables.find(v=>v.id===key)?.initial??0,op:'eq'}:{})})}/>}<Select label={uiText("StateEditor.115")} value={c.op} options={(typeof c.value==='number'?[['eq',uiText("StateEditor.110")],['ne',uiText("StateEditor.109")],['ge',uiText("StateEditor.114")],['gt',uiText("StateEditor.113")],['le',uiText("StateEditor.112")],['lt',uiText("StateEditor.111")]]:[['eq',uiText("StateEditor.110")],['ne',uiText("StateEditor.109")]]) as [string,string][]} onChange={op=>update({op})}/>{c.source==='location'?<Select label={uiText("StateEditor.108")} value={String(c.value)} options={locs} onChange={v=>update({value:v})}/>:<Scalar label={uiText("StateEditor.107")} value={c.value} options={c.source==='variable'?variable?.options:c.source==='quest'?['available','completed','undiscovered']:undefined} onChange={v=>update({value:v})}/>}<Select label={uiText("StateEditor.106")} value={c.actor_id} options={actors} onChange={actor_id=>update({actor_id})}/><button className="text-button" type="button" aria-label={uiText("StateEditor.105")} onClick={()=>set(rows.filter((_,j)=>j!==i))}>{uiText("StateEditor.001")}</button></div>;
  })}<button type="button" className="secondary" disabled={rows.length>=12} onClick={()=>set([...rows,{...condition(first),op:'eq',value:variables[0]?.initial??0}])}>{uiText("StateEditor.002")}</button></div>;
  const effects=(rows:Effect[],set:(v:Effect[])=>void)=><div className="state-subform"><strong>{uiText("StateEditor.003")}</strong>{rows.map((e,i)=>{
    const update=(patch:Partial<Effect>)=>set(rows.map((v,j)=>i===j?{...v,...patch}:v));
    const source={set:'variable',add:'variable',resource:'resource',clock:'clock',reveal:'knowledge'}[e.kind]||'';
    const variable=variables.find(v=>v.id===e.target);
    return <div className="state-row" key={i}><Select label={uiText("StateEditor.104")} value={e.kind} options={Object.entries(kinds)} onChange={kind=>{const source={set:'variable',add:'variable',resource:'resource',clock:'clock',reveal:'knowledge'}[kind]||'';update({kind,target:targets(source)[0]?.[0]||null,value:kind==='set'?variables[0]?.initial??0:1,text:kind==='message'?uiText("StateEditor.103"):''});}}/>{source&&<Select label={uiText("StateEditor.102")} value={e.target||''} options={targets(source)} onChange={target=>update({target,...(e.kind==='set'?{value:variables.find(v=>v.id===target)?.initial??0}:{})})}/>}<Select label={uiText("StateEditor.101")} value={e.actor_id} options={actors} onChange={actor_id=>update({actor_id})}/>{e.kind==='message'?<Input label={uiText("StateEditor.100")} value={e.text} onChange={text=>update({text})}/>:e.kind!=='reveal'&&<Scalar label={uiText("StateEditor.099")} value={e.value} options={e.kind==='set'?variable?.options:undefined} onChange={v=>update({value:v})}/>}<button className="text-button" type="button" aria-label={uiText("StateEditor.098")} onClick={()=>set(rows.filter((_,j)=>j!==i))}>{uiText("StateEditor.001")}</button></div>;
  })}<button type="button" className="secondary" disabled={rows.length>=6} onClick={()=>set([...rows,freshEffect()])}>{uiText("StateEditor.004")}</button></div>;
  const sample=()=>{
    const progress=ident(scope+'_progress'),ready=ident(scope+'_ready'),act=ident(scope+'_study');
    onChange({variables:[{id:progress,name:uiText("StateEditor.097"),kind:'integer',initial:0,minimum:0,maximum:3,options:[],visibility:'public'},{id:ready,name:uiText("StateEditor.096"),kind:'boolean',initial:false,minimum:0,maximum:100,options:[],visibility:'player'}],actions:[{id:act,name:uiText("StateEditor.095"),description:uiText("StateEditor.094"),location_id:null,when_all:[],when_any:[],effects:[effect(progress)],once:false,cooldown_s:0,time_cost_s:60}],triggers:[{id:ident(scope+'_breakthrough'),name:uiText("StateEditor.093"),on:'turn',target_id:null,when_all:[{...condition(progress),value:2}],when_any:[],effects:[{...effect(ready),kind:'set',value:true},{kind:'message',target:null,actor_id:pc,value:0,text:uiText("StateEditor.092")}],once:true,cooldown_s:0}],tests:[{name:uiText("StateEditor.091"),steps:[{kind:'state_action',target_id:act,seconds:60},{kind:'state_action',target_id:act,seconds:60}],expect:[{...condition(ready),op:'eq',value:true}]}]});setOpen(true);
  };
  return <section className="state-editor"><h3>{uiText("StateEditor.005")}</h3><p className="tiny-muted">{uiText("StateEditor.006", {p0: (scope==='world'?uiText("StateEditor.090"):uiText("StateEditor.089"))})}</p>{!value?<div className="provider-buttons"><button type="button" className="secondary" onClick={sample}>{uiText("StateEditor.007")}</button><button type="button" className="text-button" onClick={()=>{onChange(empty());setOpen(true);}}>{uiText("StateEditor.008")}</button></div>:<><button type="button" className="secondary" onClick={()=>setOpen(!open)}>{uiText("StateEditor.009", {p0: (open?uiText("StateEditor.088"):uiText("StateEditor.087")), p1: (pack.variables.length), p2: (pack.actions.length), p3: (pack.triggers.length)})}</button>{open&&<>
    <h4>{uiText("StateEditor.010")}</h4>{pack.variables.map((v,i)=><details className="editor-block" key={i}><summary>{v.name} · {String(v.initial)}</summary><div className="form-grid"><Input label={uiText("StateEditor.086")} value={v.name} onChange={s=>change(p=>{p.variables[i].name=s;})}/><Input label={uiText("StateEditor.085")} value={v.id} onChange={s=>change(p=>{p.variables[i].id=s;})}/><Select label={uiText("StateEditor.084")} value={v.kind} options={[["integer",uiText("StateEditor.083")],["boolean",uiText("StateEditor.082")],["enum",uiText("StateEditor.081")]]} onChange={s=>change(p=>{const kind=s as Variable['kind'];Object.assign(p.variables[i],{kind,initial:kind==='integer'?0:kind==='boolean'?false:uiText("StateEditor.080"),options:kind==='enum'?[uiText("StateEditor.080"),uiText("RoomPanel.063"),uiText("StateEditor.079")]:[]});})}/><Select label={uiText("StateEditor.078")} value={v.visibility} options={[["public",uiText("StateEditor.077")],["player",uiText("StateEditor.076")],["gm",uiText("StateEditor.075")]]} onChange={s=>change(p=>{p.variables[i].visibility=s as Variable['visibility'];})}/><Scalar label={uiText("StateEditor.074")} value={v.initial} options={v.options} onChange={s=>change(p=>{p.variables[i].initial=s;})}/>{v.kind==='integer'&&<><Input label={uiText("StateEditor.073")} type="number" value={v.minimum} onChange={s=>change(p=>{p.variables[i].minimum=Number(s)||0;})}/><Input label={uiText("StateEditor.072")} type="number" value={v.maximum} onChange={s=>change(p=>{p.variables[i].maximum=Number(s)||0;})}/></>}{v.kind==='enum'&&<Input label={uiText("StateEditor.071")} value={v.options.join(',')} onChange={s=>change(p=>{p.variables[i].options=s.split(/[,，]/).map(s=>s.trim()).filter(Boolean);})}/>}</div><button type="button" className="text-button" onClick={()=>change(p=>{p.variables.splice(i,1);})}>{uiText("StateEditor.011")}</button></details>)}<button type="button" className="secondary" disabled={pack.variables.length>=32} onClick={()=>change(p=>{p.variables.push({id:ident(scope+'_value'),name:uiText("StateEditor.070"),kind:'integer',initial:0,minimum:0,maximum:100,options:[],visibility:'public'});})}>{uiText("StateEditor.012")}</button>
    <h4>{uiText("StateEditor.013")}</h4>{pack.actions.map((a,i)=><details className="editor-block" key={i}><summary>{a.name}</summary><div className="form-grid"><Input label={uiText("StateEditor.069")} value={a.name} onChange={v=>change(p=>{p.actions[i].name=v;})}/><Input label={uiText("StateEditor.068")} value={a.id} onChange={v=>change(p=>{p.actions[i].id=v;})}/><Input label={uiText("StateEditor.067")} value={a.description} onChange={v=>change(p=>{p.actions[i].description=v;})}/><Select label={uiText("StateEditor.066")} value={a.location_id||''} options={[["",uiText("StateEditor.065")],...locs]} onChange={v=>change(p=>{p.actions[i].location_id=v||null;})}/><Input label={uiText("StateEditor.064")} type="number" value={a.time_cost_s} onChange={v=>change(p=>{p.actions[i].time_cost_s=Number(v)||1;})}/><Input label={uiText("StateEditor.063")} type="number" value={a.cooldown_s} onChange={v=>change(p=>{p.actions[i].cooldown_s=Number(v)||0;})}/></div><label className="checkboxes"><input type="checkbox" checked={a.once} onChange={e=>change(p=>{p.actions[i].once=e.target.checked;})}/>{uiText("StateEditor.014")}</label>{conditions(a.when_all,v=>change(p=>{p.actions[i].when_all=v;}),uiText("StateEditor.047"))}{conditions(a.when_any,v=>change(p=>{p.actions[i].when_any=v;}),uiText("StateEditor.046"))}{effects(a.effects,v=>change(p=>{p.actions[i].effects=v;}))}<button type="button" className="text-button" onClick={()=>change(p=>{p.actions.splice(i,1);})}>{uiText("StateEditor.015")}</button></details>)}<button type="button" className="secondary" disabled={pack.actions.length>=16||!variables.length} onClick={()=>change(p=>{p.actions.push({id:ident(scope+'_action'),name:uiText("StateEditor.062"),description:'',location_id:null,when_all:[],when_any:[],effects:[freshEffect()],once:false,cooldown_s:0,time_cost_s:60});})}>{uiText("StateEditor.016")}</button>
    <h4>{uiText("StateEditor.017")}</h4>{pack.triggers.map((t,i)=><details className="editor-block" key={i}><summary>{t.name}</summary><div className="form-grid"><Input label={uiText("StateEditor.061")} value={t.name} onChange={v=>change(p=>{p.triggers[i].name=v;})}/><Input label={uiText("StateEditor.060")} value={t.id} onChange={v=>change(p=>{p.triggers[i].id=v;})}/><Select label={uiText("StateEditor.059")} value={t.on} options={[["turn",uiText("StateEditor.058")],["move",uiText("StateEditor.057")],["state_action",uiText("StateEditor.056")],["reveal",uiText("StateEditor.055")],["challenge",uiText("StateEditor.054")],["attack",uiText("StateEditor.053")],["rest",uiText("StateEditor.052")],["say",uiText("StateEditor.051")],["wait",uiText("StateEditor.050")]]} onChange={v=>change(p=>{p.triggers[i].on=v;p.triggers[i].target_id=null;})}/>{!['turn','say','wait'].includes(t.on)&&<Input label={uiText("StateEditor.049")} value={t.target_id||''} onChange={v=>change(p=>{p.triggers[i].target_id=v||null;})}/>}<Input label={uiText("StateEditor.048")} type="number" value={t.cooldown_s} onChange={v=>change(p=>{p.triggers[i].cooldown_s=Number(v)||0;})}/></div><label className="checkboxes"><input type="checkbox" checked={t.once} onChange={e=>change(p=>{p.triggers[i].once=e.target.checked;if(!e.target.checked&&!p.triggers[i].cooldown_s)p.triggers[i].cooldown_s=60;})}/>{uiText("StateEditor.018")}</label>{conditions(t.when_all,v=>change(p=>{p.triggers[i].when_all=v;}),uiText("StateEditor.047"))}{conditions(t.when_any,v=>change(p=>{p.triggers[i].when_any=v;}),uiText("StateEditor.046"))}{effects(t.effects,v=>change(p=>{p.triggers[i].effects=v;}))}<button type="button" className="text-button" onClick={()=>change(p=>{p.triggers.splice(i,1);})}>{uiText("StateEditor.019")}</button></details>)}<button type="button" className="secondary" disabled={pack.triggers.length>=24||!variables.length} onClick={()=>change(p=>{p.triggers.push({id:ident(scope+'_trigger'),name:uiText("StateEditor.045"),on:'turn',target_id:null,when_all:[],when_any:[],effects:[freshEffect()],once:true,cooldown_s:0});})}>{uiText("StateEditor.020")}</button>
    <h4>{uiText("StateEditor.021")}</h4><p className="tiny-muted">{uiText("StateEditor.022")}</p>{pack.tests.map((t,i)=><details className="editor-block" key={i}><summary>{uiText("StateEditor.023", {p0: (t.name), p1: (t.steps.length)})}</summary><Input label={uiText("StateEditor.044")} value={t.name} onChange={v=>change(p=>{p.tests[i].name=v;})}/>{t.steps.map((s,j)=><div className="state-row" key={j}><Select label={uiText("StateEditor.043")} value={s.kind} options={[["state_action",uiText("StateEditor.042")],["move",uiText("StateEditor.041")],["reveal",uiText("StateEditor.040")],["challenge",uiText("StateEditor.039")],["attack",uiText("GamePanel.016")],["rest",uiText("GamePanel.015")],["wait",uiText("RoomPanel.042")],["say",uiText("StateEditor.038")]]} onChange={v=>change(p=>{p.tests[i].steps[j].kind=v;p.tests[i].steps[j].target_id=['wait','say'].includes(v)?null:v==='state_action'?pack.actions[0]?.id||'':v==='move'?locs[0][0]:v==='challenge'?'challenge_0':v==='attack'?'enemy_'+(props.enemies?.[0]?.id||''):v==='rest'?pc:'fact_clue_0';})}/>{!['wait','say'].includes(s.kind)&&<Select label={uiText("StateEditor.037")} value={s.target_id||''} options={s.kind==='state_action'?[...props.inherited?.actions||[],...pack.actions].map(a=>[a.id,a.name]):s.kind==='move'?locs:s.kind==='attack'?(props.enemies||[]).map(e=>['enemy_'+e.id,e.name||uiText("StateEditor.036")]):s.kind==='rest'?[[pc,uiText("StateEditor.035")]]:s.kind==='challenge'?(props.challenges||[]).map((c,i)=>['challenge_'+i,c.title||uiText("SimulationEditor.021")]):facts} onChange={v=>change(p=>{p.tests[i].steps[j].target_id=v;})}/>}<Input label={uiText("StateEditor.034")} type="number" value={s.seconds} onChange={v=>change(p=>{p.tests[i].steps[j].seconds=Number(v)||1;})}/><button type="button" className="text-button" onClick={()=>change(p=>{p.tests[i].steps.splice(j,1);})}>{uiText("StateEditor.024")}</button></div>)}<button type="button" className="secondary" disabled={t.steps.length>=24} onClick={()=>change(p=>{p.tests[i].steps.push({kind:pack.actions.length?'state_action':'wait',target_id:pack.actions[0]?.id||null,seconds:60});})}>{uiText("StateEditor.025")}</button>{conditions(t.expect,v=>change(p=>{p.tests[i].expect=v;}),uiText("StateEditor.033"))}<button type="button" className="text-button" onClick={()=>change(p=>{p.tests.splice(i,1);})}>{uiText("StateEditor.026")}</button></details>)}<button type="button" className="secondary" disabled={pack.tests.length>=12} onClick={()=>change(p=>{p.tests.push({name:uiText("StateEditor.032"),steps:p.actions.map(a=>({kind:'state_action',target_id:a.id,seconds:60})),expect:[{...condition(first),op:'eq',value:variables[0]?.initial??0}]});})}>{uiText("StateEditor.027")}</button>
    </>}</>}</section>;
}

export type CustomState = {variables:{id:string;name:string;kind:string;minimum:number;maximum:number;value:Value}[];actions:{id:string;name:string;description:string}[]};
export function StatePanel({value,busy,onAction}:{value?:CustomState;busy:boolean;onAction:(text:string,id:string)=>void}){
  useLocale();
  if(!value)return null;
  return <section className="sidebar-section custom-state-panel"><h3>{uiText("StateEditor.028")}</h3>{value.variables.map(v=><div className="custom-state-value" key={v.id}><span>{v.name}</span><strong>{typeof v.value==='boolean'?v.value?uiText("StateEditor.031"):uiText("StateEditor.030"):v.value}</strong>{v.kind==='integer'&&<progress max={v.maximum-v.minimum||1} value={Number(v.value)-v.minimum}/>}</div>)}<div className="rule-actions">{value.actions.map(a=><button key={a.id} className="rule-action" disabled={busy} title={a.description} onClick={()=>onAction(uiText("StateEditor.029", {p0: (a.name)}),a.id)}>{a.name}</button>)}</div></section>;
}
